config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'devise_custom/sessions', registrations: 'devise_custom/registrations', omniauth_callbacks: 'devise_custom/omniauth_callbacks' }

  authenticated :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :users, only: %i[show edit update index] do
    member do
      patch :update_to_organizer
      patch :update_to_admin
      get :edit_default_password
      patch :update_default_password
    end

    get :search_users, on: :collection
  end

  resources :events, only: %i[index show new create destroy edit update] do
    get :list_archived, on: :collection

    member do
      patch :add_organizer
      delete :remove_organizer
    end

    resources :attendances do
      member do
        patch 'change_status/:new_status', action: :change_status, as: 'change_status'
        delete :destroy
      end

      collection do
        get :pending_attendances
        get :search
        get :user_info
      end
    end

    resources :registration_groups, only: %i[new destroy show create edit update]

    resources :payments, only: [] do
      member { post :checkout }
    end

    resources :registration_periods, only: %i[new create destroy edit update]
    resources :registration_quotas, only: %i[new create destroy edit update]
  end

  root to: 'events#index'
end

app/models/registration_period.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: registration_periods
#
#  created_at :timestamptz      not null
#  end_at     :timestamptz
#  event_id   :bigint(8)
#  id         :bigint(8)        not null, primary key
#  price      :decimal(10, )    not null
#  start_at   :timestamptz
#  title      :string(255)
#  updated_at :timestamptz      not null
#

class RegistrationPeriod < ApplicationRecord
  belongs_to :event

  has_many :attendances, dependent: :restrict_with_exception

  scope :for, ->(analysed_date) { where(':analysed_date BETWEEN start_at AND end_at', analysed_date: analysed_date).order('id desc') }
  scope :ending_after, ->(datetime) { where('? < end_at', datetime).order('id desc') }

  validates :title, :start_at, :end_at, :price, presence: true
end

app/controllers/registration_periods_controller.rb
# frozen_string_literal: true

class RegistrationPeriodsController < AuthenticatedController
  before_action :assign_event
  before_action :check_organizer
  before_action :assign_period, only: %i[destroy edit update]

  def new
    @period = RegistrationPeriod.new
  end

  def create
    @period = RegistrationPeriod.new(period_params.merge(event: @event))
    if @period.save
      @period = RegistrationPeriod.new
      redirect_to event_path(@event)
    else
      render :new
    end
  end

  def destroy
    @period.destroy
    redirect_to @event
  end

  def edit; end

  def update
    return redirect_to @event if @period.update(period_params)

    render :edit
  end

  private

  def assign_period
    @period = @event.registration_periods.find(params[:id])
  end

  def period_params
    params.require(:registration_period).permit(:title, :start_at, :end_at, :price)
  end
end

app/views/registration_periods/_form.html.erb
<%= form_for [@event, @period], class: 'form' do |f| %>
  <div class="row">
    <div class="col-xl-6 form-group">
      <%= f.label :title, class: 'control-label' %>
      <%= f.text_field :title, class: 'form-control', autofocus: true %>
      <span class="help-block"><%= @period.errors[:title].join(', ') %></span>
    </div>
    <div class="col-xl-6 form-group">
      <%= f.label :price, class: 'control-label' %>
      <%= f.number_field :price, class: 'form-control' %>
      <span class="help-block"><%= @period.errors[:price].join(', ') %></span>
    </div>
  </div>
  <div class="row">
    <div class="col-xl-6 form-group">
      <%= f.label :start_at, class: 'control-label' %>
      <%= f.datetime_field :start_at, class: 'form-control' %>
      <span class="help-block"><%= @period.errors[:start_at].join(', ') %></span>
    </div>
    <div class="col-xl-6 form-group">
      <%= f.label :end_at, class: 'control-label' %>
      <%= f.datetime_field :end_at, class: 'form-control' %>
      <span class="help-block"><%= @period.errors[:end_at].join(', ') %></span>
    </div>
  </div>

  <div class="row">
    <div class="col-xl-12 form-group">
      <%= f.submit class: 'btn btn-success text-label button-spacing' %>
    </div>
  </div>
<% end %>

app/views/registration_periods/_periods_list.html.erb
<h5><%= t('reistration_periods.index.title') %></h5>

<%= link_to t('registration_periods.new.title'), new_event_registration_period_path(@event), class: 'btn btn-sm btn-success bottom-spaced-component float-right' %>

<% if event.registration_periods.present? %>
  <table class="table">
    <thead>
      <th><%= RegistrationPeriod.human_attribute_name :id %></th>
      <th><%= RegistrationPeriod.human_attribute_name :title %></th>
      <th><%= RegistrationPeriod.human_attribute_name :start_at %></th>
      <th><%= RegistrationPeriod.human_attribute_name :end_at %></th>
      <th><%= I18n.t('registration_periods.attendances.pending') %></th>
      <th><%= I18n.t('registration_periods.attendances.paid') %></th>
      <th><%= I18n.t('registration_periods.attendances.confirmed') %></th>
      <th><%= I18n.t('registration_periods.attendances.total') %></th>
      <th><%= RegistrationPeriod.human_attribute_name :price %></th>
      <th></th>
    </thead>
    <tbody>
      <% event.registration_periods.each do |period| %>
        <tr id="<%="period_#{period.id}" %>">
          <td><%= period.id %></td>
          <td><%= period.title %></td>
          <td><%= l(period.start_at, format: :short) %></td>
          <td><%= l(period.end_at, format: :short) %></td>
          <td><%= period.attendances.pending.count %></td>
          <td><%= period.attendances.paid.count %></td>
          <td><%= period.attendances.confirmed.count %></td>
          <td><%= period.attendances.not_cancelled.count %></td>
          <td><%= number_to_currency(period.price) %></td>
          <td>
            <%= link_to event_registration_period_path(event, period), data: { confirm: t('general.confirm' ) }, method: :delete do %>
              <i class="far fa-trash-alt"></i>
            <% end %>
            <%= link_to edit_event_registration_period_path(event, period) do %>
              <i class="far fa-edit"></i>
            <% end %>
          </td>
        </tr>

      <% end %>
    </tbody>
  </table>
<% else %>
  <h5><i><%= t('general.no_data') %></i></h5>
<% end %>

app/views/registration_periods/edit.html.erb
<div class="breadcrumb">
  <div class="row">
    <div class="col-xl-12">
      <%= link_to t('events.index.title'), events_path %>
      >

      <%= link_to @event.name, event_path(@event) %>
      >

      <%= t('registration_periods.edit.title') %>
    </div>
  </div>
</div>

<%= render 'form' %>

app/views/registration_periods/new.html.erb
<div class="breadcrumb">
  <div class="row">
    <div class="col-xl-12">
      <%= link_to t('events.index.title'), events_path %>
      >

      <%= link_to @event.name, event_path(@event) %>
      >

      <%= t('registration_periods.new.title') %>
    </div>
  </div>
</div>

<%= render 'form' %>