config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'devise_custom/sessions', registrations: 'devise_custom/registrations', omniauth_callbacks: 'devise_custom/omniauth_callbacks' }

  authenticated :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :users, only: %i[show edit update index] do
    member do
      patch :update_to_organizer
      patch :update_to_admin
      get :edit_default_password
      patch :update_default_password
    end

    get :search_users, on: :collection
  end

  resources :events, only: %i[index show new create destroy edit update] do
    get :list_archived, on: :collection

    member do
      patch :add_organizer
      delete :remove_organizer
    end

    resources :attendances do
      member do
        patch 'change_status/:new_status', action: :change_status, as: 'change_status'
        delete :destroy
      end

      collection do
        get :pending_attendances
        get :search
        get :user_info
      end
    end

    resources :registration_groups, only: %i[new destroy show create edit update]

    resources :payments, only: [] do
      member { post :checkout }
    end

    resources :registration_periods, only: %i[new create destroy edit update]
    resources :registration_quotas, only: %i[new create destroy edit update]
  end

  root to: 'events#index'
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  birth_date             :date
#  city                   :string(255)
#  confirmation_sent_at   :timestamptz
#  confirmation_token     :string(255)      indexed
#  confirmed_at           :timestamptz
#  country                :string(255)
#  created_at             :timestamptz      not null
#  current_sign_in_at     :timestamptz
#  current_sign_in_ip     :string(255)
#  disability             :integer          default("disability_not_informed"), not null, indexed
#  education_level        :integer          default("no_education_informed"), indexed
#  email                  :string(255)      not null, indexed
#  encrypted_password     :string(255)      default(""), not null
#  ethnicity              :integer          default("no_ethnicity_informed"), not null, indexed
#  failed_attempts        :bigint(8)        default(0), not null
#  first_name             :string(255)      not null
#  gender                 :integer          default("gender_not_informed"), indexed
#  id                     :bigint(8)        not null, primary key
#  last_name              :string(255)      not null
#  last_sign_in_at        :timestamptz
#  last_sign_in_ip        :string(255)
#  locked_at              :timestamptz
#  registration_group_id  :bigint(8)        indexed
#  remember_created_at    :timestamptz
#  reset_password_sent_at :timestamptz
#  reset_password_token   :string(255)      indexed
#  role                   :bigint(8)        default("user"), not null
#  roles_mask             :bigint(8)
#  school                 :string
#  sign_in_count          :bigint(8)        default(0), not null
#  state                  :string(255)
#  unconfirmed_email      :string(255)
#  unlock_token           :string(255)      indexed
#  updated_at             :timestamptz      not null
#  user_image             :string(255)
#
# Indexes
#
#  idx_4539890_fk_rails_ebe9fba698                  (registration_group_id)
#  idx_4539890_index_users_on_confirmation_token    (confirmation_token) UNIQUE
#  idx_4539890_index_users_on_email                 (email) UNIQUE
#  idx_4539890_index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  idx_4539890_index_users_on_unlock_token          (unlock_token) UNIQUE
#  index_users_on_disability                        (disability)
#  index_users_on_education_level                   (education_level)
#  index_users_on_ethnicity                         (ethnicity)
#  index_users_on_gender                            (gender)
#
# Foreign Keys
#
#  fk_rails_ebe9fba698  (registration_group_id => registration_groups.id) ON DELETE => restrict ON UPDATE => restrict
#

class User < ApplicationRecord
  enum role: { user: 0, organizer: 1, admin: 2 }
  enum gender: { cisgender_man: 0, transgender_man: 1, cisgender_woman: 2, transgender_woman: 3, non_binary: 4, gender_not_informed: 5 }
  enum education_level: { no_education_informed: 0, primary: 1, secondary: 2, tec_secondary: 3, tec_terciary: 4, bachelor: 5, master: 6, doctoral: 7 }
  enum ethnicity: { no_ethnicity_informed: 0, asian: 1, white: 2, indian: 3, brown: 4, black: 5 }
  enum disability: { no_disability: 0, visually_impairment: 1, hearing_impairment: 2, physical_impairment: 3, mental_impairment: 4, disability_not_informed: 5 }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :lockable, :omniauthable

  devise :omniauthable, omniauth_providers: %i[github]

  mount_uploader :user_image, RegistrationsImageUploader

  has_many :attendances, dependent: :destroy
  has_many :events, -> { distinct }, through: :attendances, dependent: :nullify
  has_many :invoices, through: :attendances, dependent: :destroy
  has_many :led_groups, class_name: 'RegistrationGroup', inverse_of: :leader, foreign_key: :leader_id, dependent: :nullify
  has_many :registered_attendances, class_name: 'Attendance', inverse_of: :registered_by_user, foreign_key: :registered_by_id, dependent: :restrict_with_exception

  has_and_belongs_to_many :organized_events, class_name: 'Event'

  validates :first_name, :last_name, presence: true, length: { maximum: 100 }
  validates :email, format: { with: /\A([\w.%+\-]+)@([\w\-]+\.)+(\w{2,})\z/i, allow_blank: true }
  validates :email, uniqueness: { case_sensitive: false, allow_blank: true }

  def self.from_omniauth(omniauth_params)
    name = omniauth_params.info.name
    where(email: omniauth_params.info.email).first_or_create do |user|
      name_parts = name.split
      user.first_name = name_parts.shift
      user.last_name = if name_parts.empty?
                         user.first_name
                       else
                         name_parts.join(' ')
                       end

      user.password = Devise.friendly_token[0, 20]
    end
  end

  def user_locale
    return 'pt' if country == 'BR' || country == 'PT' || country.blank?

    'en'
  end

  def registrations_for_event(event)
    Attendance.where(id: attendances.select { |attendance| attendance.event_id == event.id }.map(&:id))
  end

  def registrations_for_other_users
    Attendance.where(id: (registered_attendances - attendances).map(&:id)).order(registration_date: :desc)
  end

  def valid_attendance_for_event(event)
    registrations_for_event(event).not_cancelled.first
  end

  def full_name
    [first_name&.titleize, last_name&.titleize].join(' ')
  end

  def organizer_of?(event)
    return false if user?
    return true if admin?

    organized_events.include?(event)
  end

  def toggle_admin
    if admin?
      update(role: :user)
    else
      update(role: :admin)
    end
  end

  def toggle_organizer
    if organizer?
      update(role: :user)
    else
      update(role: :organizer)
    end
  end

  def avatar_valid?
    return false if user_image.blank?

    NetServices.instance.url_found?(user_image.url)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < AuthenticatedController
  before_action :assign_user, except: %i[index search_users search_users]
  before_action :check_admin, only: %i[index update_to_organizer update_to_admin]
  before_action :check_user, only: %i[show edit update]
  skip_before_action :authenticate_user!, only: %i[edit_default_password update_default_password]

  def show
    params[:id] ||= current_user.id
    active_events = @user.attendances.active.map(&:event)
    @events_for_today = Event.active_for(Time.zone.today) - active_events
  end

  def edit; end

  def update
    if @user.update(update_user_params)
      flash[:notice] = I18n.t('users.update.success')
      return redirect_to user_path(@user)
    end

    flash[:error] = @user.errors.full_messages.join(' | ')
    render :edit
  end

  def index
    @users_list = UserRepository.instance.search_engine(params[:role_index], params[:search])
  end

  def update_to_organizer
    @user.toggle_organizer
    redirect_to users_path
  end

  def update_to_admin
    @user.toggle_admin
    redirect_to users_path
  end

  def edit_default_password; end

  def update_default_password
    @user.password = update_default_password_params[:password]
    @user.password_confirmation = update_default_password_params[:update_default_password_params]

    if @user.valid?
      @user.save
      sign_in @user
      redirect_to root_path, notice: I18n.t('users.completed_login.success')
    else
      flash[:error] = @user.errors.full_messages.join(', ')
      render :edit_default_password
    end
  end

  def search_users
    @users_list = UserRepository.instance.search_engine(params[:roles], params[:search])
    respond_to { |format| format.js { render 'users/search_users' } }
  end

  private

  def assign_user
    @user = User.find(params[:id])
  end

  def update_user_params
    params.require(:user).permit(:user_image, :first_name, :last_name, :email, :country, :state, :city, :ethnicity, :disability, :school, :education_level, :gender, :birth_date)
  end

  def update_default_password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def check_user
    return if current_user.admin?

    not_found if current_user.id != @user.id
  end
end

app/helpers/user_helper.rb
module UserHelper

  def gender_options(selected_value = :gender_not_informed)
    options_for_select(User.genders.map { |gender_value, _key| [I18n.t("activerecord.attributes.user.enums.gender.#{gender_value}"), gender_value] }, selected_value)
  end

  def disability_options(selected_value)
    options_for_select(User.disabilities.map { |disability_values, _key| [I18n.t("activerecord.attributes.user.enums.disability.#{disability_values}"), disability_values] }, selected_value)
  end

  def ethnicity_options(selected_value = :no_ethnicity_informed)
    options_for_select(User.ethnicities.map { |ethnicity_values, _key| [I18n.t("activerecord.attributes.user.enums.ethnicity.#{ethnicity_values}"), ethnicity_values] }, selected_value)
  end

  def education_level_options(selected_value = :no_education_informed)
    options_for_select(User.education_levels.map { |education, _key| [I18n.t("activerecord.attributes.user.enums.education_level.#{education}"), education] }, selected_value)
  end
end

app/views/users/_event_organizers_list.html.erb
<h5><%= t('events.show.organizers.list') %></h5>

<%= form_tag add_organizer_event_path(@event), class: 'form', method: :patch, remote: true do %>
  <div class="row">
    <div class="col-xl-10 col-sm-6 form-group">
      <%= select_tag :organizer, options_for_select(@organizers_to_select.map { |u| [u.full_name, u.id] }), include_blank: t('events.show.organizers.select'), class: 'form-control' %>
    </div>
    <div class="col-xl-2 col-sm-6 form-group">
      <div class="input-group-btn">
        <button class="btn btn-light" type="submit"><i class="fa fa-plus"></i></button>
      </div>
    </div>
  </div>
<% end %>

<% if organizers_list.present? %>
  <table class="table table-stripped">
    <thead>
      <tr>
        <th><%= User.human_attribute_name(:first_name) %></th>
        <th><%= User.human_attribute_name(:email) %></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% organizers_list.each do |user| %>
        <tr>
          <td><%= link_to user.full_name, user_path(user) %></td>
          <td><%= user.email %></td>
          <td>
            <%= link_to remove_organizer_event_path(@event, organizer: user.id), method: :delete, data: { confirm: t('general.confirm' ) }, remote: true do %>
              <i class="fa fa-ban" data-toggle="tooltip" data-placement="bottom" title=<%= "#{t('events.show.organizers.remove')}" %>></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h5><i><%= t('general.no_data') %></i></h5>
<% end %>

app/views/users/_form.html.erb
<h5 class="aligned-center bottom-spaced-component font-italic"><%= I18n.t('users.new.form.diversity_message') %></h5>

<%= form_for @user, html: { class: "form-container" } do |f| %>
  <div class="row">
    <div class="col-xl-2 form-group">
      <% if @user.avatar_valid? %>
        <%= image_tag @user.user_image.url, size: '150x150', class: 'user-avatar' %>
      <% else %>
        <%= image_tag 'https://res.cloudinary.com/agile-alliance-brazil/image/upload/v1623596492/150-1503945_transparent-user-png-default-user-image-png-png_jsthbv.png', size: '150x131', class: 'user-avatar' %>
      <% end %>
    </div>
    <div class="col-xl-10 form-group">
      <%= f.file_field :user_image, class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <div class="col-xl-3 col-sm-6 form-group">
      <%= f.label :first_name, class: 'control-label' %>
      <%= f.text_field :first_name, class: 'form-control', autofocus: true %>
      <span class="help-block"><%= @user.errors[:first_name].join(', ') %></span>
    </div>
    <div class="col-xl-3 col-sm-6 form-group">
      <%= f.label :last_name, class: 'control-label' %>
      <%= f.text_field :last_name, class: 'form-control' %>
      <span class="help-block"><%= @user.errors[:last_name].join(', ') %></span>
    </div>
    <div class="col-xl-3 col-sm-6 form-group">
      <%= f.label :email, class: 'control-label' %>
      <%= f.text_field :email, class: 'form-control' %>
      <span class="help-block"><%= @user.errors[:email].join(', ') %></span>
    </div>
    <div class="col-xl-3 col-sm-6 form-group">
      <%= f.label :birth_date, class: 'control-label' %>
      <%= f.date_field :birth_date, class: 'form-control' %>
      <span class="help-block"><%= @user.errors[:gender].join(', ') %></span>
    </div>
  </div>

  <div class="row">
    <div class="col-xl col-sm-6 form-group">
      <%= f.label :gender, class: 'control-label' %>
      <%= f.select :gender, gender_options(@user.gender), {}, class: 'form-control' %>
      <span class="help-block"><%= @user.errors[:gender].join(', ') %></span>
    </div>
    <div class="col-xl col-sm-6 form-group">
      <%= f.label :disability, class: 'control-label' %>
      <%= f.select :disability, disability_options(@user.disability), {}, class: 'form-control' %>
    </div>

    <% if I18n.locale == :pt %>
      <div class="col-xl col-sm-6 form-group">
        <%= f.label :ethnicity, class: 'control-label' %>
        <%= f.select :ethnicity, ethnicity_options(@user.ethnicity), {}, class: 'form-control' %>
      </div>
    <% end %>
  </div>

  <div class="row">
    <div class="col-xl-4 col-sm-6 form-group">
      <%= f.label :country, class: 'control-label' %>
      <%= f.country_select :country, priority_countries = ["Brazil"], options = {}, html_options = { class: 'form-control' } %>
      <span class="help-block"><%= @user.errors[:country].join(', ') %></span>
    </div>
    <div class="col-xl-4 form-group">
      <%= f.label :state, class: 'control-label' %>
      <%= f.text_field :state, class: 'form-control' %>
      <span class="help-block"><%= @user.errors[:state].join(', ') %></span>
    </div>
    <div class="col-xl-4 form-group">
      <%= f.label :city, class: 'control-label' %>
      <%= f.text_field :city, class: 'form-control' %>
      <span class="help-block"><%= @user.errors[:city].join(', ') %></span>
    </div>
  </div>

  <div class="row">
    <div class="col-xl-4 col-sm-6 form-group">
      <%= f.label :education_level, class: 'control-label' %>
      <%= f.select :education_level, education_level_options(@user.education_level), {}, class: 'form-control' %>
      <span class="help-block"><%= @user.errors[:education_level].join(', ') %></span>
    </div>
    <div class="col-xl-4 col-sm-6 form-group">
      <%= f.label :school, class: 'control-label' %>
      <%= f.text_field :school, class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <div class="col-xl-12 form-group">
      <%= f.submit class: 'btn btn-success text-label button-spacing' %>
    </div>
  </div>
<% end %>

app/views/users/_user.html.erb
%div{id: "user_#{user.id}", class: 'row'}
  %div{class: 'col-lg-2 line'}
    = link_to "#{user.last_name}, #{user.first_name}", user_path(user), method: :get
  %div{class: 'col-lg-4 line'}
    = user.email
  %div{class: 'col-lg-3 centered line'}
    - unless user.admin?
      =
    - unless
      = link_to '+ organizer', update_to_organizer_user_path(user), class: 'btn-sm btn-primary', remote: true, method: :patch

app/views/users/_user_details.html.erb
<div class="row bottom-spaced-component">
  <div class="col-xl">
    <% if user.avatar_valid? %>
      <%= image_tag user.user_image.url, size: '150x150', class: 'user-avatar' %>
    <% else %>
      <%= image_tag 'https://res.cloudinary.com/agile-alliance-brazil/image/upload/v1623596492/150-1503945_transparent-user-png-default-user-image-png-png_jsthbv.png', size: '150x131' %>
    <% end %>
  </div>

  <div class="col-xl">
    <p>
      <b><%= I18n.t('activerecord.attributes.user.name') %>:</b>
      <%= user.full_name %>
    </p>
    <p>
      <b><%= I18n.t('activerecord.attributes.user.email') %>:</b>
      <%= user.email %>
    </p>
    <p>
      <b><%= I18n.t('activerecord.attributes.user.education_level') %>:</b>
      <%= I18n.t("activerecord.attributes.user.enums.education_level.#{user.education_level}") %>
    </p>
    <p>
      <b><%= I18n.t('activerecord.attributes.user.school') %>:</b>
      <%= user.school %>
    </p>
  </div>

  <div class="col-xl">
    <p>
      <b><%= I18n.t('activerecord.attributes.user.gender') %>:</b>
      <%= I18n.t("activerecord.attributes.user.enums.gender.#{user.gender}") %>
    </p>
    <% if I18n.locale == :pt %>
      <p>
        <b><%= I18n.t('activerecord.attributes.user.ethnicity') %>:</b>
        <%= I18n.t("activerecord.attributes.user.enums.ethnicity.#{user.ethnicity}") %>
      </p>
    <% end %>
    <p>
      <b><%= I18n.t('activerecord.attributes.user.disability') %>:</b>
      <%= I18n.t("activerecord.attributes.user.enums.disability.#{user.disability}") %>
    </p>
    <p>
      <b><%= I18n.t('activerecord.attributes.user.birth_date') %>:</b>
      <% if user.birth_date.present? %>
        <%= I18n.l(user.birth_date) %>
      <% else %>
        <%= I18n.t('general.not_informed') %>
      <% end %>
    </p>
  </div>

  <div class="col-xl">
    <p>
      <b><%= I18n.t('activerecord.attributes.user.country') %>:</b>
      <% if user.country.present? %>
        <%= ISO3166::Country[user.country].translations[I18n.locale.to_s] %>
      <% else %>
        <%= I18n.t('general.not_informed') %>
      <% end %>
    </p>
    <p>
      <b><%= I18n.t('activerecord.attributes.user.state') %>:</b>
      <%= user.state %>
    </p>
    <p>
      <b><%= I18n.t('activerecord.attributes.user.city') %>:</b>
      <%= user.city %>
    </p>
  </div>
</div>

<div class="row">
  <div class="col-xl">
    <%= link_to t('users.show.edit.button'), edit_user_path(user), class: 'btn btn-sm btn-primary' if user == current_user %>
  </div>
</div>

app/views/users/_users_list.html.erb
<table class="table table-stripped">
  <thead>
    <tr>
      <th><%= User.human_attribute_name(:first_name) %></th>
      <th><%= User.human_attribute_name(:email) %></th>
      <th><%= t('activerecord.attributes.user.admin') %></th>
      <th><%= t('activerecord.attributes.user.organizer') %></th>
    </tr>
  </thead>
  <tbody>
    <% @users_list.each do |user| %>
      <tr>
        <td><%= link_to user.full_name, user_path(user) %></td>
        <td><%= user.email %></td>
        <td>
          <% if user.admin? %>
            <%= link_to update_to_admin_user_path(user), method: :patch do %>
              <i class="fas fa-toggle-on fa-2x"></i>
            <% end %>
          <% else %>
            <%= link_to update_to_admin_user_path(user), method: :patch do %>
              <i class="fas fa-toggle-off fa-2x"></i>
            <% end %>
          <% end %>
        </td>
        <td>
          <% if user.organizer? %>
            <%= link_to update_to_organizer_user_path(user), method: :patch do %>
              <i class="fas fa-toggle-on fa-2x"></i>
            <% end %>
          <% else %>
            <%= link_to update_to_organizer_user_path(user), method: :patch do %>
              <i class="fas fa-toggle-off fa-2x"></i>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class="breadcrumb">
  <div class="row">
    <div class="col-xl-12">
      <%= link_to I18n.t('events.index.title'), events_path %>
      >
      <%= link_to I18n.t('users.show.title'), user_path(@user) %>
      >
      <%= I18n.t('users.edit.title') %>
    </div>
  </div>
</div>

<div>
  <div class="row">
    <div class="col-xl-12">
      <%= render 'users/form', event: @event %>
    </div>
  </div>
</div>

app/views/users/edit_default_password.html.erb
<div class="row justify-content-xl-center">
  <div class="col-xs-4 col-xs-offset-4">

    <h2><%= t('devise.passwords.change_password.title') %></h2>

    <%= form_for @user, url: update_default_password_user_path(@user), method: :patch, class: 'form-horizontal' do |f| %>
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, autofocus: true, autocomplete: 'off', class: 'form-control' %>
        <% if @minimum_password_length %>
          <span class="help-block"><%= t('devise.passwords.minimum', minimum_length_value: @minimum_password_length) %></span>
        <% end %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, autocomplete: 'off', class: 'form-control' %>
      </div>

      <div class="actions">
        <%= f.submit t('devise.registrations.change_password'), class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="breadcrumb">
  <div class="row">
    <div class="col-xl-12">
      <%= link_to t('events.index.title'), events_path %>
      >
      <%= t('users.index.title') %>
    </div>
  </div>
</div>

<%= form_tag search_users_users_path, class: 'form', method: :get, remote: true do %>
  <div class="row">
    <div class='col-xl-4 form-group'>
      <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: t('users.index.search_email') %>
    </div>
    <div class='col-xl-4 form-group'>
      <%= select_tag :roles, options_for_select(User.roles.map { |role, _| [I18n.t("activerecord.attributes.user.enums.role.#{role}"), role] }), { include_blank: t('users.index.search_roles'), class: 'form-control' } %>
    </div>
    <div class="input-group-btn">
      <button class="btn btn-light" type="submit"><i class="fa fa-search"></i></button>
    </div>
  </div>
<% end %>

<div id="users_list">
  <%= render 'users_list' %>
</div>

app/views/users/search_users.js.erb
$("#users_list").html("<%= escape_javascript(render 'users/users_list', users_list: @users_list) %>")

app/views/users/show.html.erb
<div class="breadcrumb">
  <div class="row">
    <div class="col-xl-12">
      <%= link_to t('events.index.title'), events_path %>
      >
      <%= I18n.t('users.show.title') %>
    </div>
  </div>
</div>

<%= render 'users/user_details', user: @user %>

<hr />

<%= render 'attendances/attendances_list', attendances_list: @user.attendances.order(created_at: :desc), attendances_list_csv: AttendanceExportService.to_csv(@user.attendances.order(created_at: :desc)), list_title: t('attendances.index.title') %>

<%= render 'attendances/attendances_list', attendances_list: @user.registrations_for_other_users.order(created_at: :desc), attendances_list_csv: AttendanceExportService.to_csv(@user.registered_attendances.order(created_at: :desc)), list_title: t('attendances.index.other_attendances') %>