config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'devise_custom/sessions', registrations: 'devise_custom/registrations', omniauth_callbacks: 'devise_custom/omniauth_callbacks' }

  authenticated :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :users, only: %i[show edit update index] do
    member do
      patch :update_to_organizer
      patch :update_to_admin
      get :edit_default_password
      patch :update_default_password
    end

    get :search_users, on: :collection
  end

  resources :events, only: %i[index show new create destroy edit update] do
    get :list_archived, on: :collection

    member do
      patch :add_organizer
      delete :remove_organizer
    end

    resources :attendances do
      member do
        patch 'change_status/:new_status', action: :change_status, as: 'change_status'
        delete :destroy
      end

      collection do
        get :pending_attendances
        get :search
        get :user_info
      end
    end

    resources :registration_groups, only: %i[new destroy show create edit update]

    resources :payments, only: [] do
      member { post :checkout }
    end

    resources :registration_periods, only: %i[new create destroy edit update]
    resources :registration_quotas, only: %i[new create destroy edit update]
  end

  root to: 'events#index'
end

app/models/registration_quota.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: registration_quotas
#
#  closed                :boolean          default(FALSE)
#  created_at            :timestamptz
#  event_id              :bigint(8)
#  id                    :bigint(8)        not null, primary key
#  order                 :bigint(8)
#  price                 :decimal(10, )    not null
#  quota                 :bigint(8)
#  registration_price_id :bigint(8)
#  updated_at            :timestamptz
#

class RegistrationQuota < ApplicationRecord
  belongs_to :event

  has_many :attendances, dependent: :restrict_with_exception

  validates :order, :quota, :price, presence: true

  def vacancy?
    places_sold = reserved + attendances.active.size
    open? && places_sold < quota
  end

  def capacity_left
    quota - (attendances.active.size + reserved)
  end

  private

  def open?
    !closed
  end

  def reserved
    RegistrationGroupRepository.instance.reserved_for_quota(self)
  end
end

app/controllers/registration_quotas_controller.rb
# frozen_string_literal: true

class RegistrationQuotasController < AuthenticatedController
  before_action :assign_event
  before_action :assign_quota, only: %i[destroy edit update]

  def new
    @registration_quota = RegistrationQuota.new
  end

  def create
    @registration_quota = RegistrationQuota.new(quota_params.merge(event: @event))
    if @registration_quota.save
      @registration_quota = RegistrationQuota.new
      redirect_to event_path(@event)
    else
      render :new
    end
  end

  def destroy
    @registration_quota.destroy
    redirect_to @event
  end

  def edit; end

  def update
    return redirect_to @event if @registration_quota.update(quota_params)

    render :edit
  end

  private

  def quota_params
    params.require(:registration_quota).permit(:order, :price, :quota)
  end

  def assign_quota
    @registration_quota = @event.registration_quotas.find(params[:id])
  end
end

app/views/registration_quotas/_form.html.erb
<%= form_for [@event, @registration_quota], class: 'form' do |f| %>
  <div class="row">
    <div class="col-xl-4 form-group">
      <%= f.label :order, class: 'control-label' %>
      <%= f.text_field :order, class: 'form-control', autofocus: true %>
      <span class="help-block"><%= @registration_quota.errors[:order].join(', ') %></span>
    </div>
    <div class="col-xl-4 form-group">
      <%= f.label :price, class: 'control-label' %>
      <%= f.text_field :price, class: 'form-control' %>
      <span class="help-block"><%= @registration_quota.errors[:price].join(', ') %></span>
    </div>
    <div class="col-xl-4 form-group">
      <%= f.label :quota, class: 'control-label' %>
      <%= f.text_field :quota, class: 'form-control' %>
      <span class="help-block"><%= @registration_quota.errors[:quota].join(', ') %></span>
    </div>
  </div>
  <div class="row">
    <div class="col-xl-12 form-group">
      <%= f.submit class: 'btn btn-success text-label button-spacing' %>
    </div>
  </div>
<% end %>

app/views/registration_quotas/_quotas_list.html.erb
<h5><%= t('registration_quotas.index.title') %></h5>

<%= link_to t('registration_quotas.new.title'), new_event_registration_quota_path(@event), class: 'btn btn-sm btn-success bottom-spaced-component float-right' %>

<% if event.registration_quotas.present? %>
  <table class="table">
    <thead>
      <th><%= RegistrationQuota.human_attribute_name :id %></th>
      <th><%= RegistrationQuota.human_attribute_name :order %></th>
      <th><%= RegistrationQuota.human_attribute_name :quota %></th>
      <th><%= I18n.t('registration_quotas.attendances.pending') %></th>
      <th><%= I18n.t('registration_quotas.attendances.paid') %></th>
      <th><%= I18n.t('registration_quotas.attendances.confirmed') %></th>
      <th><%= I18n.t('registration_quotas.attendances.total') %></th>
      <th><%= RegistrationQuota.human_attribute_name :price %></th>
      <th></th>
    </thead>
    <tbody>
      <% event.registration_quotas.each do |quota| %>
        <tr id="<%="quota_#{quota.id}" %>">
          <td><%= quota.id %></td>
          <td><%= quota.order %></td>
          <td><%= quota.quota %></td>
          <td><%= quota.attendances.pending.count %></td>
          <td><%= quota.attendances.paid.count %></td>
          <td><%= quota.attendances.confirmed.count %></td>
          <td><%= quota.attendances.not_cancelled.count %></td>
          <td><%= number_to_currency(quota.price) %></td>
          <td>
            <%= link_to event_registration_quota_path(event, quota), data: { confirm: t('general.confirm' ) }, method: :delete do %>
              <i class="far fa-trash-alt"></i>
            <% end %>
            <%= link_to edit_event_registration_quota_path(event, quota) do %>
              <i class="far fa-edit"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h5><i><%= t('general.no_data') %></i></h5>
<% end %>

app/views/registration_quotas/edit.html.erb
<div class="breadcrumb">
  <div class="row">
    <div class="col-xl-12">
      <%= link_to t('events.index.title'), events_path %>
      >

      <%= link_to @event.name, event_path(@event) %>
      >

      <%= t('registration_quotas.edit.title') %>
    </div>
  </div>
</div>

<%= render 'form' %>

app/views/registration_quotas/new.html.erb
<div class="breadcrumb">
  <div class="row">
    <div class="col-xl-12">
      <%= link_to t('events.index.title'), events_path %>
      >

      <%= link_to @event.name, event_path(@event) %>
      >

      <%= t('registration_quotas.new.title') %>
    </div>
  </div>
</div>

<%= render 'form' %>