config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'devise_custom/sessions', registrations: 'devise_custom/registrations', omniauth_callbacks: 'devise_custom/omniauth_callbacks' }

  authenticated :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :users, only: %i[show edit update index] do
    member do
      patch :update_to_organizer
      patch :update_to_admin
      get :edit_default_password
      patch :update_default_password
    end

    get :search_users, on: :collection
  end

  resources :events, only: %i[index show new create destroy edit update] do
    get :list_archived, on: :collection

    member do
      patch :add_organizer
      delete :remove_organizer
    end

    resources :attendances do
      member do
        patch 'change_status/:new_status', action: :change_status, as: 'change_status'
        delete :destroy
      end

      collection do
        get :pending_attendances
        get :search
        get :user_info
      end
    end

    resources :registration_groups, only: %i[new destroy show create edit update]

    resources :payments, only: [] do
      member { post :checkout }
    end

    resources :registration_periods, only: %i[new create destroy edit update]
    resources :registration_quotas, only: %i[new create destroy edit update]
  end

  root to: 'events#index'
end

app/models/event.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: events
#
#  attendance_limit           :bigint(8)
#  city                       :string(255)      not null
#  country                    :string(255)      not null
#  created_at                 :timestamptz      not null
#  days_to_charge             :bigint(8)        default(7)
#  end_date                   :timestamptz
#  event_image                :string(255)
#  event_nickname             :string
#  event_remote               :boolean          default(FALSE)
#  event_remote_manual_link   :string
#  event_remote_platform_mail :string
#  event_remote_platform_name :string
#  event_schedule_link        :string
#  full_price                 :decimal(10, )
#  id                         :bigint(8)        not null, primary key
#  link                       :string(255)
#  main_email_contact         :string(255)      not null
#  name                       :string(255)
#  privacy_policy             :string
#  start_date                 :timestamptz
#  state                      :string(255)      not null
#  updated_at                 :timestamptz      not null
#

class Event < ApplicationRecord
  mount_uploader :event_image, RegistrationsImageUploader

  has_many :attendances, dependent: :restrict_with_exception
  has_many :registration_periods, dependent: :destroy
  has_many :registration_quotas, dependent: :destroy
  has_many :registration_groups, dependent: :destroy
  has_many :slack_configurations, dependent: :destroy, class_name: 'Slack::SlackConfiguration'

  has_and_belongs_to_many :organizers, class_name: 'User'

  validates :start_date, :end_date, :full_price, :name, :main_email_contact, :attendance_limit, :country, :state, :city, presence: true
  validate :period_valid?

  scope :active_for, ->(date) { where('end_date > ?', date) }
  scope :not_started, -> { where('start_date > ?', Time.zone.today) }
  scope :ended, -> { where('end_date < ?', Time.zone.today) }
  scope :events_to_welcome_attendances, -> { where('date(start_date) <= :limit_date AND date(end_date) >= :end_limit_date', limit_date: 4.days.from_now.to_date, end_limit_date: Time.zone.today) }

  def full?
    places_sold = reserved_count + attendances.active.size
    attendance_limit.present? && attendance_limit.positive? && (attendance_limit <= places_sold)
  end

  def registration_price_for(attendance, payment_type)
    group = attendance.registration_group
    return group.amount if group.present? && group.amount.present? && group.amount.positive?

    extract_value(attendance, payment_type)
  end

  def period_for(now = Time.zone.now)
    registration_periods.for(now).first if registration_periods.present?
  end

  def find_quota
    registration_quotas.order(order: :asc).select(&:vacancy?)
  end

  def started
    Time.zone.today >= start_date
  end

  def add_organizer(user)
    organizers << user unless organizers.include?(user)
    save
  end

  def remove_organizer(user)
    organizers.delete(user)
    save
  end

  def contains?(user)
    attendances.active.where(user: user).present?
  end

  def attendances_in_the_queue?
    !attendances.waiting.empty?
  end

  def queue_average_time
    attendances_passed_by_queue = attendances.active.with_time_in_queue
    return 0 if attendances_passed_by_queue.empty?

    attendances_passed_by_queue.sum(:queue_time) / attendances_passed_by_queue.count
  end

  def agile_alliance_discount_group?
    agile_alliance_discount_group.present?
  end

  def agile_alliance_discount_group
    registration_groups.find_by(name: 'Membros da Agile Alliance')
  end

  def capacity_left
    attendance_limit - (attendances.active.size + reserved_count)
  end

  def attendances_count
    attendances.active.count + reserved_count
  end

  def reserved_count
    RegistrationGroupRepository.instance.reserved_for_event(self)
  end

  def average_ticket
    attendances_confirmed = attendances.committed_to
    return 0 if attendances_confirmed.empty?

    attendances_confirmed.sum(:registration_value) / attendances_confirmed.count
  end

  def ended?
    end_date < Time.zone.now
  end

  def event_image_valid?
    return false if event_image.blank?

    NetServices.instance.url_found?(event_image.url)
  end

  private

  # TODO: bad logic here - fixing needed
  def extract_value(attendance, payment_type)
    quota = find_quota
    if payment_type == 'statement_agreement'
      full_price
    elsif attendance.price_band?
      attendance.band_value * attendance.discount
    elsif period_for.present?
      period_for.price * attendance.discount
    elsif quota.first.present?
      quota.first.price * attendance.discount
    else
      (full_price || 0) * attendance.discount
    end
  end

  def period_valid?
    return unless start_date.present? && end_date.present?

    errors.add(:end_date, I18n.t('activerecord.errors.models.event.attributes.end_date.invalid_period')) if start_date > end_date
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < AuthenticatedController
  before_action :assign_event, only: %i[show destroy add_organizer remove_organizer edit update]

  before_action :check_organizer, only: %i[edit update destroy add_organizer]
  before_action :check_admin, only: %i[new create list_archived]

  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @events = Event.includes(:registration_periods).all.select { |event| event.end_date.present? && event.end_date >= Time.zone.now }
  end

  def show
    assign_organizers
    @last_attendance_for_user = AttendanceRepository.instance.attendances_for(@event, current_user).last if current_user.present?
  end

  def list_archived
    @events = Event.includes(:registration_periods).ended.order(start_date: :desc)
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to event_path(@event)
    else
      render :new
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_path }
    end
  end

  def add_organizer
    organizer = User.find(params[:organizer])
    return not_found unless organizer.organizer? || organizer.admin?

    @event.add_organizer(organizer)
    assign_organizers
    respond_to { |format| format.js { render 'events/add_organizer' } }
  end

  def remove_organizer
    organizer = User.find(params[:organizer])
    @event.remove_organizer(organizer)
    assign_organizers
    respond_to { |format| format.js { render 'events/add_organizer' } }
  end

  def edit; end

  def update
    if @event.update(event_params)
      redirect_to @event
    else
      render :edit
    end
  end

  private

  def assign_organizers
    @organizers_to_select = User.organizer.order(:first_name, :last_name) - @event.organizers
  end

  def event_params
    params.require(:event).permit(:event_image, :name, :attendance_limit, :days_to_charge, :start_date, :end_date, :city, :state, :country, :main_email_contact, :full_price, :link, :event_nickname, :event_remote, :event_remote_platform_mail, :event_remote_platform_name, :event_remote_manual_link, :event_schedule_link, :privacy_policy)
  end

  def assign_event
    @event = Event.find(params[:id])
  end
end

app/views/events/_event_tabs.html.erb
<div class="row">
  <div class="col-xl-12">
    <ul class="nav nav-tabs">

      <li class="nav-item <%= 'active' if details_tab %>">
        <%= link_to t('general.details.title'), '#', class: 'nav-link' %>
      </li>
    </ul>
  </div>
</div>

app/views/events/_events.html.erb
<div class="row">
  <% events.each do |event| %>
    <div class="col-xl-4">
      <div class="card event-card">
        <% if event.event_image_valid? %>
          <%= image_tag event.event_image.url, size: '200x180', class: 'card-img-top' %>
        <% else %>
          <%= image_tag 'https://res.cloudinary.com/agile-alliance-brazil/image/upload/v1623597789/img-empty_b8hdek.png', size: '200x180', class: 'card-img-top' %>
        <% end %>

        <div class="card-body">
          <% if current_user&.organizer_of?(event) %>
            <h5 class="card-title"><%= link_to event.name, event_attendances_path(event) %></h5>
          <% else %>
            <h5 class="card-title"><%= event.name %></h5>
          <% end %>
          <p class="card-text small"><%= l(event.start_date.to_date) %></p>
          <p class="card-text small"><%= number_to_currency(event.registration_price_for(Attendance.new, :gateway)) %></p>

          <% if current_user.present? && current_user.registrations_for_event(event).not_cancelled.present? %>
            <%= link_to event_attendance_path(event, current_user.valid_attendance_for_event(event)), class: 'event-action-item' do %>
              <i class="fa fa-eye"></i>
              <%= I18n.t('attendandes.show.title') %>
            <% end %>
          <% else %>
            <%= link_to new_event_attendance_path(event), class: 'event-action-item' do %>
              <i class="fa fa-plus-square"></i>
              <%= I18n.t('attendandes.new.title') %>
            <% end %>

          <% end %>

          <% if current_user&.admin? %>
            <%= link_to event_path(event), class: 'float-right' do %>
              <i class="fas fa-cogs"></i>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/events/_form.html.erb
<%= form_for event do |f| %>
  <div class="row">
    <div class="col-xl-3 form-group">
      <% if @event.event_image_valid? %>
        <%= image_tag @event.event_image.url, size: '300x300', class: 'card-img-top' %>
      <% else %>
        <%= image_tag 'https://res.cloudinary.com/agile-alliance-brazil/image/upload/v1623597789/img-empty_b8hdek.png', size: '300x300' %>
      <% end %>
    </div>
    <div class="col-xl-9 form-group">
      <%= f.file_field :event_image, class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <div class="col-xl-4 form-group">
      <%= f.label :name, class: 'control-label' %>
      <%= f.text_field :name, class: 'form-control', autofocus: true %>
      <span class="help-block"><%= event.errors[:name].join(', ') %></span>
    </div>
    <div class="col-xl-4 form-group">
      <%= f.label :event_nickname, class: 'control-label' %>
      <%= f.text_field :event_nickname, class: 'form-control' %>
    </div>
    <div class="col-xl-4 form-group">
      <%= f.label :attendance_limit, class: 'control-label' %>
      <%= f.text_field :attendance_limit, class: 'form-control' %>
      <span class="help-block"><%= event.errors[:attendance_limit].join(', ') %></span>
    </div>
  </div>

  <div class="row">
    <div class="col-xl-6 form-group">
      <%= f.label :main_email_contact, class: 'control-label' %>
      <%= f.text_field :main_email_contact, class: 'form-control' %>
      <span class="help-block"><%= event.errors[:main_email_contact].join(', ') %></span>
    </div>
    <div class="col-xl-6 form-group">
      <%= f.label :days_to_charge, class: 'control-label' %>
      <%= f.text_field :days_to_charge, class: 'form-control' %>
      <span class="help-block"><%= event.errors[:days_to_charge].join(', ') %></span>
    </div>
  </div>

  <div class="row">
    <div class="col-xl-6 form-group">
      <%= f.label :city, class: 'control-label' %>
      <%= f.text_field :city, class: 'form-control' %>
      <span class="help-block"><%= event.errors[:city].join(', ') %></span>
    </div>
    <div class="col-xl-4 form-group">
      <%= f.label :state, class: 'control-label' %>
      <%= f.text_field :state, class: 'form-control' %>
    </div>
    <div class="col-xl-2 form-group">
      <%= f.label :country, class: 'control-label' %>
      <%= f.country_select :country, priority_countries = ["Brazil"], options = {}, html_options = { class: 'form-control' } %>
    </div>
  </div>

  <div class="row">
    <div class="col-xl-6 form-group">
      <%= f.label :start_date, class: 'control-label' %>
      <%= f.datetime_field :start_date, class: 'form-control' %>
      <span class="help-block"><%= event.errors[:start_date].join(', ') %></span>
    </div>
    <div class="col-xl-6 form-group">
      <%= f.label :end_date, class: 'control-label' %>
      <%= f.datetime_field :end_date, class: 'form-control' %>
      <span class="help-block"><%= event.errors[:end_date].join(', ') %></span>
    </div>
  </div>

  <div class="row">
    <div class="col-xl-3 form-group">
      <%= f.label :full_price, class: 'control-label' %>
      <%= f.text_field :full_price, class: 'form-control' %>
      <span class="help-block"><%= event.errors[:full_price].join(', ') %></span>
    </div>
    <div class="col-xl-3 form-group">
      <%= f.label :link, class: 'control-label' %>
      <%= f.text_field :link, class: 'form-control' %>
    </div>
    <div class="col-xl-3 form-group">
      <%= f.label :event_schedule_link, class: 'control-label' %>
      <%= f.text_field :event_schedule_link, class: 'form-control' %>
    </div>
    <div class="col-xl-3 form-group">
      <%= f.label :privacy_policy, class: 'control-label' %>
      <%= f.text_field :privacy_policy, class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <div class="col-xl-3 form-group">
      <%= f.check_box :event_remote %>
      <%= f.label :event_remote, class: 'form-check-label' %>
    </div>
    <div class="col-xl-3 form-group">
      <%= f.label :event_remote_platform_name, class: 'control-label' %>
      <%= f.text_field :event_remote_platform_name, class: 'form-control' %>
    </div>
    <div class="col-xl-3 form-group">
      <%= f.label :event_remote_platform_mail, class: 'control-label' %>
      <%= f.text_field :event_remote_platform_mail, class: 'form-control' %>
    </div>
    <div class="col-xl-3 form-group">
      <%= f.label :event_remote_manual_link, class: 'control-label' %>
      <%= f.text_field :event_remote_manual_link, class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <div class="col-xl-12 form-group">
      <%= f.submit class: 'btn btn-success text-label button-spacing' %>
    </div>
  </div>
<% end %>

app/views/events/_registration_periods.html.haml
- if current_user.try(:organizer?) || current_user.try(:admin?)
  - if event.registration_periods.present?
    %table.table
      %th= t('formtastic.labels.registration_period.id')
      %th= t('formtastic.labels.registration_period.start_at')
      %th= t('formtastic.labels.registration_period.end_at')
      %th= t('formtastic.labels.registration_period.value')
      - @event.registration_periods.each do |period|
        %tr{ id: "period_#{period.id}" }
          %td= period.id
          %td= l(period.start_at)
          %td= l(period.end_at)
          %td= period.price
  - else
    %h3= t('events.show.no_periods_message')

app/views/events/_registration_quotas.html.haml
- if current_user.try(:organizer?) || current_user.try(:admin?)
  %h4= t('reistration_quotas.list')

  - if event.registration_quotas.present?
    %table.table
      %th= t('formtastic.labels.registration_quota.id')
      %th= t('formtastic.labels.registration_quota.quota')
      %th= t('formtastic.labels.registration_quota.value')
      %th= t('formtastic.labels.registration_quota.active_attendances')
      - @event.registration_quotas.each do |quota|
        %tr{ id: "quota_#{quota.id}" }
          %td= quota.id
          %td= quota.quota
          %td= number_to_currency quota.price
          %td= quota.attendances.active.count
  - else
    %h3= t('events.show.no_periods_message')

app/views/events/add_organizer.js.erb
$('#organizers-list').html("<%= escape_javascript(render 'users/event_organizers_list', organizers_list: @event.organizers.order(:first_name, :last_name)) %>")

app/views/events/edit.html.erb
<div class="breadcrumb">
  <div class="row">
    <div class="col-xl-12">
      <%= link_to t('events.index.title'), events_path %>
      >

      <%= link_to @event.name, event_path(@event) %>
      >

      <%= t('events.edit.title') %>
    </div>
  </div>
</div>

<%= render 'form', event: @event %>

app/views/events/index.html.erb
<% if current_user&.admin? %>
  <%= render 'layouts/menu', past_events_active: false, current_events_active: true, users_list_active: false, account_active: false %>
<% end %>

<div class="tab-container-<%= current_user&.admin? ? 'admin' : 'user' %>">
  <% if current_user&.admin? %>
    <div class="row bottom-spaced-component">
      <div class="col-xl-12 col-sm-8">
        <div class="float-right"><%= link_to t('events.new.title'), new_event_path, class: 'btn btn-sm btn-success' %></div>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="col-xl-12 col-sm-8">
      <div id="events">
        <% if @events.empty? %>
          <div class="no-data"><i class="far fa-calendar-alt fa-4x"></i></div>
          <div class="no-data"><%= t('general.no_data') %></div>
        <% else %>
          <%= render 'events/events', events: @events %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% content_for :javascript do %>
  <%= javascript_include_tag 'shared/nav_tabs' %>
<% end %>

app/views/events/list_archived.html.erb
<%= render 'layouts/menu', past_events_active: true, current_events_active: false, users_list_active: false, account_active: false %>

<div class="tab-container-admin">
  <div class="row">
    <div class="col-xl-12 col-sm-8">
      <div id="events">
        <% if @events.empty? %>
          <div class="no-data"><i class="far fa-calendar-alt fa-4x"></i></div>
          <div class="no-data"><%= t('general.no_data') %></div>
        <% else %>
          <%= render 'events', events: @events %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="breadcrumb">
  <div class="row">
    <div class="col-xl-4">
      <%= link_to t('events.index.title'), events_path %>
    </div>
    <div class="col-xl-1">
      >
    </div>
    <div class="col-xl-6">
      <%= t('events.new.title') %>
    </div>
  </div>
</div>

<div class="form-container">
  <div class="row justify-content-center">
    <div class="col-xl-12">
      <%= render 'form', event: @event %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="breadcrumb">
  <div class="row">
    <div class="col-xl-12">
      <%= link_to t('events.index.title'), events_path %>
      >

      <%= @event.name %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xl-4">
    <p>
      <% if @event.event_image_valid? %>
        <%= image_tag @event.event_image.url, size: '300x300', class: 'card-img-top' %>
      <% else %>
        <%= image_tag 'https://res.cloudinary.com/agile-alliance-brazil/image/upload/v1623597789/img-empty_b8hdek.png', size: '300x300', class: 'card-img-top' %>
      <% end %>
    </p>
  </div>

  <div class="col-xl-8">
    <p><h3><%= @event.name %></h3></p>
    <p>
      <b><%= I18n.t('activerecord.attributes.event.country') %>:</b>
      <% if @event.country.present? && ISO3166::Country[@event.country].present? %>
        <%= ISO3166::Country[@event.country].translations[I18n.locale.to_s] %>
      <% else %>
        <%= I18n.t('general.not_informed') %>
      <% end %>
    </p>
    <p>
      <b><%= I18n.t('activerecord.attributes.event.state') %>:</b>
      <%= @event.state %>
    </p>
    <p>
      <b><%= I18n.t('activerecord.attributes.event.city') %>:</b>
      <%= @event.city %>
    </p>
    <p>
      <b><%= Event.human_attribute_name(:full_price) %>:</b>
      <%= number_to_currency(@event.full_price) %>
    </p>
    <p>
      <b><%= I18n.t('events.show.current_price') %>:</b>
      <%= number_to_currency(@event.registration_price_for(Attendance.new, :gateway)) %>
    </p>
    <p>
      <b><%= I18n.t('events.show.statement_agreement_price') %>:</b>
      <%= number_to_currency(@event.registration_price_for(Attendance.new, 'statement_agreement')) %>
    </p>
    <p>
      <b><%= I18n.t('events.show.student_price') %>:</b>
      <%= number_to_currency(@event.registration_price_for(Attendance.new, 'statement_agreement') / 2) %>
    </p>
    <p>
      <b><%= Event.human_attribute_name(:main_email_contact) %>:</b>
      <%= mail_to(@event.main_email_contact, @event.main_email_contact) %>
    </p>
    <p>
      <% if @event.privacy_policy %>
        <%= link_to Event.human_attribute_name(:privacy_policy), @event.privacy_policy %>
      <% else %>
      <%= I18n.t('events.show.no_policy') %>
      <% end %>
    </p>

    <% if current_user&.organizer_of?(@event) %>
      <p><%= link_to I18n.t('events.edit.title'), edit_event_path(@event), class: 'btn btn-sm btn-success' %></p>
    <% end %>
  </div>
</div>

<% if current_user&.organizer_of?(@event) %>
  <ul class="nav nav-tabs bottom-spaced-component">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="tab" href="#organizers-list"><%= I18n.t('events.show.organizers.tab') %></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#periods-list"><%= I18n.t('events.show.registration_periods.tab') %></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#quotas-list"><%= I18n.t('events.show.registration_quotes.tab') %></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#groups-list"><%= I18n.t('events.show.registration_groups.tab') %></a>
    </li>
  </ul>

  <div class="tab-content">
    <div class="tab-pane active" id="organizers-list">
      <%= render 'users/event_organizers_list', organizers_list: @event.organizers.order(:first_name, :last_name) %>
    </div>

    <div class="tab-pane fade" id="periods-list">
      <%= render 'registration_periods/periods_list', event: @event %>
    </div>
    <div class="tab-pane fade" id="quotas-list">
      <%= render 'registration_quotas/quotas_list', event: @event %>
    </div>
    <div class="tab-pane fade" id="groups-list">
      <%= render 'registration_groups/groups_list', event: @event %>
    </div>
  </div>

<% end %>

<% content_for :javascript do %>
  <%= javascript_include_tag 'registration_groups/index' %>
<% end %>